# Using node modules due to vite needing loose coupling for @emnapi/runtime
nodeLinker: node-modules
# Strictly setting down stream peer deps
packageExtensions:
    "@nx/docker@23.2.0":
        dependencies:
            nx: "23.2.0"
    "@nx/esbuild@23.2.0":
        dependencies:
            nx: "23.2.0"
    "@nx/eslint-plugin@23.2.0":
        dependencies:
            eslint: "8.57.0 || 9.0.0"
    "@nx/eslint@23.2.0":
        dependencies:
            eslint: "8.57.0 || 9.0.0"
    "@nx/js@23.2.0":
        dependencies:
            nx: "23.2.0"
    "@nx/node@23.2.0":
        dependencies:
            eslint: "8.57.0 || 9.0.0"
    "@nx/devkit@23.2.0":
        dependencies:
            nx: "23.2.0"
    "@phenomnomnominal/tsquery@6.2.0":
        dependencies:
            typescript: "5.9.3"
    "@nx/react@23.2.0":
        dependencies:
            "@babel/core": "7.14.5"
            eslint: "8.57.0 || 9.0.0"
    "@nx/playwright@23.2.0":
        dependencies:
            eslint: "8.57.0 || 9.0.0"
    "@nx/vite@23.2.0":
        dependencies:
            "vite": "8.0.0"
    "@typescript-eslint/type-utils@8.70.0":
        dependencies:
            typescript: "5.9.3"
    "@typescript-eslint/utils@8.70.0":
        dependencies:
            typescript: "5.9.3"
    "@rolldown/binding-wasm32-wasi@1.0.0-rc.9":
        # CHECK HERE if having issues with wasm implentation for node
        # Setting to optional since project shouldnt need this to function
        peerDependenciesMeta:
            "@emnapi/core":
                optional: true
            "@emnapi/runtime":
                optional: true
    "@napi-rs/wasm-runtime@1.2.4":
        # CHECK HERE if having issues with wasm implentation for node
        # Setting to optional since project shouldnt need this to function
        peerDependenciesMeta:
            "@emnapi/core":
                optional: true
            "@emnapi/runtime":
                optional: true
    "@swc-node/register@1.11.1":
        peerDependencies:
            "@swc/types": "0.1.28"
    "prettier-eslint@17.1.2":
        dependencies:
            typescript: "5.9.3"
    "rolldown@1.0.0-rc.9":
        peerDependenciesMeta:
            "@emnapi/runtime":
                optional: true

