services:
    mysql:
        image: percona:8.0
        container_name: dexxy-mysql
        cap_add:
            # Workaround for mbind errors (https://github.com/docker-library/mysql/issues/422)
            - SYS_NICE
        hostname: dexxy-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: dexxy-dev
        networks:
            - development
        volumes:
            - dexxy-mysql:/var/lib/mysql

networks:
    development:
        name: development

volumes:
    dexxy-mysql:
        external: true
